* Setup 
  
  See [[https://www.atlassian.com/git/tutorials/dotfiles][Dotfiles tutorial by Atlassian]].
  
** Install Dotfiles
   
   #+BEGIN_SRC
   git clone --bare git@github.com:fzuellich/dotfiles.git $HOME/dotfiles
   alias --save config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
   config config --local status.showUntrackedFiles no
   config checkout
   #+END_SRC

** From scratch (fish-style)

  #+BEGIN_SRC
  git init --bare $HOME/dotfiles
  alias --save config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
  config config --local status.showUntrackedFiles no
  #+END_SRC

* File manager

is [[https://wiki.archlinux.org/index.php/Thunar#Plugins_and_addons][thunar]]. There are more plugins available to mount file systems etc. 

* Images

image organizer is ~digikam~.
~feh~ for simple image viewing.

* Single-Sign-On SSH configuration
See [[https://wiki.archlinux.org/index.php/SSH_keys#ssh-agent][Archlinux Wiki]].

Required files are ~.pam_environment~ and
~.config/systemd/user/ssh-agent.service~.

Don't forget to enable and start the service:
~systemctl --user start ssh-agent~
~systemctl --user enable ssh-agent~

And add ~AddKeysToAgent yes~ to your SSH config.

* Setup pass

Install pass and gnupg

~pacman -S pass gnupg~

Generate a new key

~gnupg --ful-gen-key~ see https://wiki.archlinux.org/index.php/GnuPG#Usage for
more information.

Continue with https://wiki.archlinux.org/index.php/Pass
* Git-Setup
#+begin_src shell :results output silent
  git config --global commit.template ~/.config/git/commit-message-template.txt
#+end_src

* Fish tweaks
Emacs' =ansi-term= does not support setting the title of the terminal. Run this
once (~, b e~):

#+BEGIN_SRC shell :results output silent
  function fish_title; end; funcsave fish_title
#+END_SRC

[[https://fishshell.com/docs/current/faq.html#i-m-seeing-weird-output-before-each-prompt-when-using-screen-what-s-wrong][See fish documentation for more info.]]

* Clipboard manager
=greenclip= with =wl-clipboard=

Setup for Sway:
~bindsym $mod+c exec fish -c 'greenclip print | wofi -odi | wl-copy'~

Configure greenclip daemon to start with sway: https://wiki.archlinux.org/index.php/Sway#Manage_Sway-specific_daemons_with_systemd
